# Generated by Django 2.2.7 on 2020-04-03 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalID', models.IntegerField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('maritalStatus', models.CharField(choices=[('M', 'Married'), ('F', 'Unmarried')], max_length=20)),
                ('Children', models.IntegerField(blank=True, default=0)),
                ('height', models.FloatField(default=0.0)),
                ('bodyType', models.CharField(choices=[('S', 'Slim'), ('F', 'Fat'), ('A', 'Average')], max_length=15)),
                ('Complexion', models.CharField(choices=[('F', 'Fair'), ('VF', 'Very Fair'), ('D', 'Dark'), ('WM', 'Wheatish Medium'), ('WB', 'Wheatish Brown')], max_length=15)),
                ('blodGroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('B+', 'B+'), ('B-', 'B-')], max_length=15)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
