# Generated by Django 2.2.7 on 2020-04-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_completedprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedProfile',
        ),
    ]
