# Generated by Django 2.2.7 on 2020-04-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_completedprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedProfile',
        ),
    ]
