# Generated by Django 2.2.7 on 2020-04-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_completedprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedprofile',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
