# Generated by Django 2.2.7 on 2020-04-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200403_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedprofile',
            name='Complexion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='birth',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='blodGroup',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='bodyType',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='education',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='familyvalue',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='father',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='maritalStatus',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='mother',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='mothertongue',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='patnereducation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='patnerreligon',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='preferredmarrige',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='religon',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='residentialstatus',
            field=models.CharField(max_length=35),
        ),
    ]
