# Generated by Django 2.2.7 on 2020-04-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200405_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedprofile',
            name='Complexion',
            field=models.CharField(choices=[('F', 'Fair'), ('VF', 'Very Fair'), ('D', 'Dark'), ('WM', 'Wheatish Medium'), ('WB', 'Wheatish Brown')], max_length=30),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='birth',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='blodGroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('B+', 'B+'), ('B-', 'B-')], max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='bodyType',
            field=models.CharField(choices=[('S', 'Slim'), ('F', 'Fat'), ('A', 'Average')], max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='education',
            field=models.CharField(choices=[('Phd/Doctorate', 'Phd/Doctorate'), ('Master', 'Master'), ('MBA', 'MBA'), ('Diploma', 'Diploma'), ('HSC', 'HSC'), ('SSC', 'SSC'), ('Alim', 'Alim'), ('Dakhil', 'Dakhil'), ('Fajil', 'Fajil'), ('Kamil', 'Kamil')], max_length=50),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='familyvalue',
            field=models.CharField(choices=[('Liberal', 'Lineral'), ('Religious', 'Religious'), ('Traditional', 'Traditional'), ('Moderate', 'Moderate')], max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='father',
            field=models.CharField(choices=[('Retired', 'Retired'), ('Businessman', 'Businessman'), ('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Passed Away', 'Passed Away')], max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='maritalStatus',
            field=models.CharField(choices=[('M', 'Married'), ('F', 'Unmarried')], max_length=20),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='mother',
            field=models.CharField(choices=[('Home Maker', 'Home Maker'), ('Retired', 'Retired'), ('Businessman', 'Businessman'), ('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Passed Away', 'Passed Away')], max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='mothertongue',
            field=models.CharField(choices=[('Bengali', 'Bengali'), ('English', 'English'), ('Others', 'Others')], max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='patnereducation',
            field=models.CharField(choices=[('Phd/Doctorate', 'Phd/Doctorate'), ('Master', 'Master'), ('MBA', 'MBA'), ('Diploma', 'Diploma'), ('HSC', 'HSC'), ('SSC', 'SSC'), ('Alim', 'Alim'), ('Dakhil', 'Dakhil'), ('Fajil', 'Fajil'), ('Kamil', 'Kamil')], max_length=50),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='patnerreligon',
            field=models.CharField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Others', 'Others')], max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='preferredmarrige',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('No Matter', 'No Matter')], max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='religon',
            field=models.CharField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Others', 'Others')], max_length=35),
        ),
        migrations.AlterField(
            model_name='completedprofile',
            name='residentialstatus',
            field=models.CharField(choices=[('Rented', 'Rented'), ('Owner', 'Owner')], max_length=35),
        ),
    ]
