# Generated by Django 2.2.7 on 2020-04-05 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_auto_20200405_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalID', models.IntegerField(max_length=15)),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=11)),
                ('city', models.CharField(max_length=50)),
                ('birth', models.DateField(auto_now_add=True)),
                ('maritalStatus', models.CharField(max_length=30)),
                ('Children', models.IntegerField(default=0)),
                ('height', models.FloatField(default=0.0)),
                ('bodyType', models.CharField(max_length=35)),
                ('Complexion', models.CharField(max_length=30)),
                ('blodGroup', models.CharField(max_length=35)),
                ('religon', models.CharField(max_length=35)),
                ('mothertongue', models.CharField(max_length=35)),
                ('familyvalue', models.CharField(max_length=35)),
                ('father', models.CharField(max_length=35)),
                ('mother', models.CharField(max_length=35)),
                ('sister', models.IntegerField(default=0)),
                ('brother', models.IntegerField(default=0)),
                ('education', models.CharField(max_length=50)),
                ('universitycollege', models.CharField(default='Null', max_length=100)),
                ('profession', models.CharField(default='Null', max_length=100)),
                ('designation', models.CharField(default='Null', max_length=100)),
                ('currentlivingcourtry', models.CharField(max_length=100)),
                ('currentlivingcity', models.CharField(max_length=100)),
                ('currentlivingarea', models.CharField(max_length=100)),
                ('residentialstatus', models.CharField(max_length=35)),
                ('homecountry', models.CharField(max_length=100)),
                ('homedistrict', models.CharField(max_length=100)),
                ('aboutyou', models.TextField(max_length=300)),
                ('aboutfamily', models.TextField(max_length=300)),
                ('preferredage', models.CharField(choices=[('18-25', '18-25'), ('26-30', '26-30'), ('30-35', '30-35'), ('36-40', '36-40'), ('40-50', '40-50'), ('50+', '50+')], max_length=35)),
                ('preferredmarrige', models.CharField(max_length=35)),
                ('patnerreligon', models.CharField(max_length=35)),
                ('patnerhomecountry', models.CharField(max_length=30)),
                ('patnercurrentliving', models.CharField(max_length=30)),
                ('patnereducation', models.CharField(max_length=50)),
                ('patnerprofession', models.CharField(max_length=50)),
                ('aboutpatner', models.TextField(max_length=300)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CompletedProfile',
        ),
    ]
