# Generated by Django 2.2.7 on 2020-04-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200405_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullregister',
            name='birth',
            field=models.CharField(max_length=20),
        ),
    ]
