# Generated by Django 2.2.7 on 2020-04-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200406_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedregister',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to='profile_image'),
        ),
    ]
